[mods]
hyper = ["command", "option", "shift", "control"]

[binds]
"hyper+esc" = "sleep 0.25; pmset displaysleepnow"
"hyper+§" = "sleep 0.25; pmset sleepnow"

[layer.open]
activate = "hyper+o"
d = "open ~/Downloads"
h = "open ~"

[layer.open.code]
activate = "c"
r = "open ~/code/rust"
p = "open ~/code/py"
w = "open ~/code/web"

[layer.launch]
activate = "hyper+l"
s = "open -a Safari"
f = "open -a Finder"
g = "open -a Ghostty"
x = "open -a Xcode"
c = "open -a Google Chrome"
v = "open -a Visual Studio Code"
t = "open -a Terminal"
m = "open -a Activity Monitor"

[layer.snap]
activate = "hyper+s"
j = "snap:LeftHalf"
k = "snap:Maximize"
l = "snap:RightHalf"
"shift+j" = "snap:Left"
"shift+l" = "snap:Right"
r = "snap:Restore"
f = "snap:Fullscreen"

[layer.snap.quarters]
activate = "q"
i = "snap:TopLeftQuarter"
o = "snap:TopRightQuarter"
k = "snap:BottomLeftQuarter"
l = "snap:BottomRightQuarter"

[layer.kiwi]
activate = "hyper+i"
r = "reload"

[app."Google Chrome"]
"hyper+w" = "remap:cmd+w"
